version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "automated pr"
    reviewers:
      - "bengeois"
